// Code generated by cudago. Edit at your own risk.
package helloCuda

import (
    "github.com/InternatBlackhole/cudago/cuda"
	"unsafe"
)


//here just to force usage of unsafe package
var __kernel_useless_var__ unsafe.Pointer = nil

const (
	KeyKernel = "kernel"
)


type helloArgs struct {
    message uintptr

}

/*var (
    helloArgs = helloArgs{}

)*/







func Hello(grid, block cuda.Dim3, message uintptr) error {
	err := autoloadLib_kernel()
	if err != nil {
		return err
	}
	kern, err := getKernel("kernel", "hello")
	if err != nil {
		return err
	}
	
	params := helloArgs{
	    message: message,
	
	}
	
	return kern.Launch(grid, block, unsafe.Pointer(&params.message))
}

func HelloEx(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, message uintptr) error {
	err := autoloadLib_kernel()
	if err != nil {
		return err
	}
	kern, err := getKernel("kernel", "hello")
	if err != nil {
		return err
	}
	
	params := helloArgs{
	    message: message,
	
	}
	
	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.message))
}



var loaded_kernel = false


var pathToCompile_kernel = "kernel.cu"
func autoloadLib_kernel() error {
	var code []byte
	if loaded_kernel {
		return nil
	}
	code, err := compileFile(pathToCompile_kernel)
	if err != nil {
		return err
	}
	err = InitLibrary([]byte(code), "kernel")
	if err != nil {
		return err
	}
	loaded_kernel = true
	return nil
}

